### PR TITLE
Fixes #31. Fix default AML loading

### LINKED ISSUE #31: Default AML documents not loading
Currently both demos are not loading the default AML example documents due to the use of `window.location.origin` as the base to build URLs to load documents from. URLs point to `https://a.ml/examples/pods/dialect.yaml` instead of `https://a.ml/amf-playground/examples/pods/dialect.yaml`.

### PR DESCRIPTION
**Pull request by postatum**

### CODE REVIEW

File: docs/js/aml_playground_validation.js [hunk 1]
```diff
@@ -58476,7 +58476,7 @@ var ViewModel = /** @class */ (function () {
         this.changesFromLastUpdate = 0;
         this.someModelChanged = false;
         this.RELOAD_PERIOD = 1000;
-        this.base = window.location.origin;
+        this.base = window.location.href.toString().replace('/validation.html', '');
```
Comment (jstoiko) [inline docs/js/aml_playground_validation.js]: there is no way to make this a bit more generic instead of explicitly removing `validation.html`, remove `*.html` or get that `validation.html` dynamically (is it not part of the `window.location` object?)?

Comment (postatum) [reply docs/js/aml_playground_validation.js]: I can't think of a generic way right now. This is how it worked before I tried to use `origin`. `validation.html` is not part of `window.location`.
